/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoreRouteImport } from './routes/lore'
import { Route as ControlsRouteImport } from './routes/controls'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RulesIndexRouteImport } from './routes/rules.index'
import { Route as RulesSlugRouteImport } from './routes/rules.$slug'

const LoreRoute = LoreRouteImport.update({
  id: '/lore',
  path: '/lore',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsRoute = ControlsRouteImport.update({
  id: '/controls',
  path: '/controls',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesIndexRoute = RulesIndexRouteImport.update({
  id: '/rules/',
  path: '/rules/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesSlugRoute = RulesSlugRouteImport.update({
  id: '/rules/$slug',
  path: '/rules/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/controls': typeof ControlsRoute
  '/lore': typeof LoreRoute
  '/rules/$slug': typeof RulesSlugRoute
  '/rules/': typeof RulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/controls': typeof ControlsRoute
  '/lore': typeof LoreRoute
  '/rules/$slug': typeof RulesSlugRoute
  '/rules': typeof RulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/controls': typeof ControlsRoute
  '/lore': typeof LoreRoute
  '/rules/$slug': typeof RulesSlugRoute
  '/rules/': typeof RulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/controls' | '/lore' | '/rules/$slug' | '/rules/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/controls' | '/lore' | '/rules/$slug' | '/rules'
  id: '__root__' | '/' | '/controls' | '/lore' | '/rules/$slug' | '/rules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ControlsRoute: typeof ControlsRoute
  LoreRoute: typeof LoreRoute
  RulesSlugRoute: typeof RulesSlugRoute
  RulesIndexRoute: typeof RulesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lore': {
      id: '/lore'
      path: '/lore'
      fullPath: '/lore'
      preLoaderRoute: typeof LoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls': {
      id: '/controls'
      path: '/controls'
      fullPath: '/controls'
      preLoaderRoute: typeof ControlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/': {
      id: '/rules/'
      path: '/rules'
      fullPath: '/rules/'
      preLoaderRoute: typeof RulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/$slug': {
      id: '/rules/$slug'
      path: '/rules/$slug'
      fullPath: '/rules/$slug'
      preLoaderRoute: typeof RulesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ControlsRoute: ControlsRoute,
  LoreRoute: LoreRoute,
  RulesSlugRoute: RulesSlugRoute,
  RulesIndexRoute: RulesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
